local function assert_equal(actual, expected, message)
  if actual ~= expected then
    error((message or "values differ") .. (": expected %s, got %s"):format(expected, actual), 2)
  end
end

local script_path = debug.getinfo(1, "S").source:sub(2)
local config_root = script_path:match("(.+)/tests/") or "."
package.path = config_root .. "/lua/?.lua;" .. package.path

local locations = require("lsp_locations")

assert_equal(locations.is_generated_go_file("/project/graph/model.gen.go"), true, ".gen.go file")
assert_equal(locations.is_generated_go_file("/project/service_mock.go"), true, "_mock.go file")
assert_equal(locations.is_generated_go_file("/project/generated/model.go"), true, "generated directory")
assert_equal(locations.is_generated_go_file("/project/app/api/graphql/graph/model.go"), true, "GraphQL graph directory")
assert_equal(locations.is_generated_go_file("/project/service.go"), false, "regular Go file")
assert_equal(locations.is_generated_go_file("/project/generated/client.ts"), false, "non-Go file")

local generated_file = vim.fn.tempname() .. ".go"
vim.fn.writefile({ "// Code generated by a test. DO NOT EDIT.", "package generated" }, generated_file)
assert_equal(locations.is_generated_go_file(generated_file), true, "generated header")
vim.fn.delete(generated_file)

local filtered, excluded = locations.filter_items({
  { filename = "/project/generated/model.go" },
  { filename = "/project/model.go" },
  { filename = "/project/client.ts" },
})
assert_equal(#filtered, 2, "filtered location count")
assert_equal(excluded, 1, "excluded location count")
assert_equal(filtered[1].filename, "/project/model.go", "regular Go location retained")
assert_equal(filtered[2].filename, "/project/client.ts", "non-Go location retained")
